CC = g++ -std=c++11 -O3

all: random forward normal tnormal

random: random.cpp
	$(CC) random.cpp -o random.o

forward: forward.cpp
	$(CC) forward.cpp -o forward.o

normal: normal.cpp
	$(CC) normal.cpp -o normal.o

cauchy: cauchy.cpp
	$(CC) cauchy.cpp -o cauchy.o

tnormal: tnormal.cpp
	$(CC) tnormal.cpp -o tnormal.o
